<?php

$title = "Eliminar Observación..";
$this->headTitle($title);
//var_dump("ssssssssss"); var_dump($admin->nombre); exit();
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>¿Seguro deseas eliminar esta observación ?
</p>
<?php 
$url = $this->url('observaciones', array(
    'action' => 'delete',
    'id'     => $observacion->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name='id' value="<?php echo (int) $observacion->id;?>" />
        <input type="submit" name='del' value="Yes" />
        <input type="submit" name='del' value="No" />
    </div>
</form>
