<?php //
$title = "Agregar Usuarios a ";
$this->headTitle($title);
$form = $this->form;
?>

<h1> <?= $this->escapeHtml($title . $caracteristica); ?> </h1>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-es.js"></script>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<div id="container">
    <div class="row-fluid top-buffer">
        <div class=" text-center">
            <form action="<?php echo $this->basePath() ?>/usuarios/addusuariosestadisticas" id="formaddval" method="post" name="formaddval">
                <table id="tblprod2" class="table table-hover table-bordered">
                    <tr>
                        <td class="td_table">Nombres </td>
                        <td><input type="text" name="nombres" id="nombres"  class="form-control validate[required]" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Apellidos </td>
                        <td><input type="text" name="apellidos" id="apellidos"  class="form-control validate[required]" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Carrera </td>
                        <td>
                        <select name="carrera" id="carrera" class="form-control validate[required]">
                        <?php  $getCarrera = $universidad->getCarrera(); 
                            foreach ($getCarrera as $selecCarrera){  ?>
                            <option value="<?= $selecCarrera->ID_CARRERA ?> " > <?= $selecCarrera->NOMBRE ?></option>
                            <?php } ?>
                         </select>     
                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Universidad </td>
                        <td>
                        <select name="universidad" id="universidad" class="form-control validate[required]">
                        <?php  $getUniversidades = $universidad->getUniversidad(); 
                            foreach ($getUniversidades as $selecUniversidades){ ?>
                            <option value="<?= $selecUniversidades->ID_UNIVERSIDAD ?> " > <?= $selecUniversidades->NOMBRE ?></option>
                            <?php } ?>
                         </select>     
                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Correo Electrónico </td>
                        <td><input type="text" name="email" id="email"  class="form-control validate[required]" /></td>
                    </tr>
                </table>
                <button id="addAdmin" class="btn btn-success" type="submit" >Guardar</button>
            </form>
        </div>
    </div>
</div>


<!--<div id="container">
    <div class="row-fluid top-buffer">
        <div class=" text-center">
            <form action="<?php echo $this->basePath() ?>/usuarios/addusuariosestadisticas" id="formaddval" method="post" name="formaddval">
                <table id="tblprod2" class="table table-hover table-bordered">
                    <tr>
                        <td class="td_table">Nombre </td>
                        <td><input type="text" name="observa[]" id="observa"  class="form-control validate[required]" /></td>
                        <td class="td_table"><a id="agregarCampo" class="btn btn-info" href="#">Agregar <br/> Observación</a>
                    </tr>
                    
                    <tr>
                        <td class="td_table">Carrera o universidad </td>
                        <td><input type="text" name="universa[]" id="universa"  class="form-control validate[required]" /></td>
                        <td class="td_table"><a id="agregarCampo" class="btn btn-info" href="#">Agregar <br/> Observación</a>
                    </tr>
                    <tr>
                         <td class="td_table"></td>
                         <td class="td_table">
                        <div id="contenedor"></div>
                         </td>
                        
                    </tr>
                    <tr>
                         <td class="td_table">Carrera o universidad</td>
                         <td class="td_table">
                        <div id="contenedor2"></div>
                         </td>
                    </tr>
                    
                    
                </table>
                <button id="addAdmin" class="btn btn-success" type="submit" >Guardar</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function () {
        var MaxInputs = 8; //Número Maximo de Campos
        var contenedor = $("#contenedor"); //ID del contenedor
        
        var AddButton = $("#agregarCampo"); //ID del Botón Agregar

        //var x = número de campos existentes en el contenedor
        var x = $("#contenedor div").length + 1;
        var FieldCount = x - 1; //para el seguimiento de los campos

        $(AddButton).click(function (e) {
            if (x <= MaxInputs) //max input box allowed
            {
                FieldCount++;
                //agregar campo
//                $(contenedor).append('<div><textarea class="form-control validate[required]" name="observa[]" id="campo_' + FieldCount + '" placeholder="Texto ' + FieldCount + '" rows="3"></textarea><a href="#" class="eliminar">&times;</a></div>');
                $(contenedor).append('<div><td><input type="text" name="observa[]" id="campo_"  class="form-control validate[required]" /><a href="#" class="eliminar">&times;</a></td><td><input type="text" name="universa[]" id="campo_"  class="form-control validate[required]" /><a href="#" class="eliminar">&times;</a></td></div>');
                
                x++; //text box increment
            }
            return false;
        });

        $("body").on("click", ".eliminar", function (e) { //click en eliminar campo
            if (x > 1) {
                $(this).parent('div').remove(); //eliminar el campo
                x--;
            }
            return false;
        });
    });
</script>-->