<?php
$title = "Modificar Estudiante";
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<div id="container">
    <div class="row-fluid top-buffer">
        <div class=" text-center">
            <form action="<?php echo $this->basePath() ?>/usuarios/edit" id="formadd" method="post" name="formadd">
                <table id="tblprod" class="table table-hover table-bordered">
                    <tr>
                        <td class="td_table">Nombres</td>
                        <td><input class="form-control validate[required]" type="text" name="name" id="name" value="<?php echo $this->nombre ?>" />
                            <input class="form-control validate[required]" type="hidden" name="id" id="id" value="<?php echo $this->id ?>" />
                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Apellidos</td>
                        <td><input type="text" class="form-control validate[required]" name="last_name" id="last_name" value="<?php echo $this->last_name ?>"  /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Correo Electronico</td>
                        <td><input type="email" class="form-control validate[required]" name="email" id="email" value="<?php echo $this->email ?>" /> </td>
                    </tr>
                    
                    <tr>
                        <td class="td_table">Otro Correo Electrónico</td>
                        <td><input type="email" class="form-control validate[required]" name="otro_email" id="otro_email" value="<?php echo $this->otro_email ?>" /> </td>
                    </tr>
                    
                    
                    <tr>
                        <td class="td_table">Telefono</td>
                        <td><input type="text" class="form-control validate[required]" name="telefono" id="telefono" value="<?php echo $this->telefono ?>" /></td>
                    </tr>
                    
                    <tr>
                        <td class="td_table">Celular</td>
                        <td><input type="text" class="form-control validate[required]" name="celular" id="celular" value="<?php echo $this->celular ?>" /></td>
                    </tr>
                    
                    <tr>
                        <td class="td_table">Código</td>
                        <td><input type="text" class="form-control validate[required]" name="cod_estud" id="cod_estud" value="<?php echo $this->cod_estud ?>" /> </td>
                    </tr>
                    <tr>
                        <td class="td_table">Programa académico / Universidad</td>
                        <td>
                            <select name="prog_academic" class="form-control validate[required]">
                                <?php
                                $ProgramaAcademico = $progAcademico->getAllProgramasAcademicos();
                                foreach ($ProgramaAcademico as $progAcademico) {//
                                    ?>
                                    <option value="<?php echo $progAcademico->ID_CARRERA ?>"><?php echo $progAcademico->NOMBRE ?> </option>
                                    <?php
                                }
                                ?>
                            </select>


                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Semestre</td>
                        <td><input type="number" class="form-control validate[required]" name="semestre" id="semestre" value="<?php echo $this->semestre ?>" /> </td>
                    </tr>
                    <tr>
                        <td class="td_table">Programa de Intenres</td>
                        <td>
                            <select name="prog_interes" id="prog_interes" class="form-control validate[required]">
                                <?php
                                $ProgramaInteres = $progInteres->getAllProgramasInteres();
                                foreach ($ProgramaInteres as $progInteres) {
                                    ?>
                                    <option value="<?= $progInteres->id ?>"><?php echo $progInteres->name ?> </option>
                                    <?php
                                }
                                ?>

                            </select>
                            <input type="text" class="form-control validate[required]" id="otro_prog_interes" name="otro_prog_interes" value="" style="display:none;" />

                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Compromisos</td>
                        <td><textarea class="form-control validate[required]" name="compromisos" id="compromisos" rows="3"><?php echo $this->compromisos ?></textarea> </td>
                    </tr>
                    <tr>
                        <td class="td_table">Observaciones</td>
                        <td><textarea class="form-control validate[required]" name="observaciones" id="observaciones" rows="3"><?php echo $this->observaciones ?></textarea> </td>
                        <td style="width: 1px;"><a id="agregarCampo" class="btn btn-info" href="#">Agregar <br/> Observación</a>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <div id="contenedor">
                                <div class="added">
                                    <div class="observaciones">
                                        <table style="width: 100%; border: 1px solid; border-color: #BDBDBD;" background-color="#FFFFFF"  >
                                            <tr>
                                                <td class="td_table" style="text-align: center; border: 1px solid; border-color: #BDBDBD;">Observación</td>
                                                <td class="td_table" style="text-align: center; border: 1px solid; border-color: #BDBDBD;">Fecha</td>
                                                <td class="td_table" style="text-align: center; border: 1px solid; border-color: #BDBDBD;">Administrador</td>
                                                <td class="td_table" style="text-align: center; border: 1px solid; border-color: #BDBDBD;">Eliminar</td>
                                            </tr>
                                        <?php
                                        $getObservaciones = $observacionesUsuario->getObservacionesUsers($this->id);
                                        foreach ($getObservaciones as $observacionesss) {
                                            //var_dump($observacionesss); exit();
                                            ?>
                                        <style type="text/css"> .observaciones { overflow: scroll; height:315px; } </style>
                                        
                                            <tr>
                                                <td style="border: 1px solid; width: 50%; border-color: #BDBDBD;">
                                                   <textarea class="form-control validate[required]" name="observaM[]" rows="3" readonly> <?= $observacionesss->observacion ?></textarea>
                                                </td>
                                                <td style="border: 1px solid; border-color: #BDBDBD;">
                                                    <?= $observacionesss->dateCreation ?>
                                                </td>
                                                <td style="border: 1px solid; border-color: #BDBDBD;">
                                                    <?= $observacionesss->NOMBRE . " " . $observacionesss->APELLIDO ?>
                                                </td>
                                                <td class="th_table"><a href="<?php echo $this->url('observaciones', array('action' => 'delete', 'id' => $observacionesss->id)); ?>"><img src='<?php echo $this->basePath('img/eliminar.png') ?>' ></a></td>
                                            </tr>
                                        
                                            
                                            
                                            <input type="hidden" name="idobservaM[]" value="<?= $observacionesss->id ?>"/>
                                            <?php }
                                        ?>
                                            </table>
                                    </div>
<!--                                    <input type="text" name="mitexto[]" id="campo_1" placeholder="Texto 1"/><a href="#" class="eliminar">&times;</a>-->
                                </div>
                            </div>
                        </td>
                        <?php if(isset($observacionesss->idUser)){ ?>
                        <td style="width: 1px;"><a class="btn btn-info" href="<?php echo $this->url('observaciones', array('action' => 'index', 'id' => $observacionesss->idUser)); ?>">Ver <br/> Observaciones</a>
                        </td>
                        <?php } ?>
                    </tr>
                    <?php
                    $estado = "";
                    if ($this->estado == 1) {
                        $estado = "Consulta";
                    } else if ($this->estado == 2) {
                        $estado = "Tramite";
                    } else if ($this->estado == 3) {
                        $estado = "Paso a Movilidad";
                    } else if ($this->estado == 4) {
                        $estado = "Se respondio";
                    } else if ($this->estado == 5) {
                        $estado = "No paso nada";
                    }
                    ?>
                    <tr>
                        <td class="td_table">Estado</td>
                        <td>
                            <select name="estado" id="estado" class="form-control validate[required]">
                                <option value="<?php echo $this->estado ?>"><?php echo $estado ?></option>
                                <option value="1">Consulta</option>
                                <option value="2">Tramite</option>
                                <option value="3">Paso a Movilidad</option>
                                <option value="4">Se respondio</option>
                                <option value="5">No paso nada</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                       <td class="td_table">Fecha de Compromiso</td> 
                       <td><input class="form-control validate[required]" type="date" id="fechaCompromiso" name="fechaCompromiso" value="<?php echo $fechaCompromiso ?>" /> </td>
                    </tr>
                </table>
                <button id="addUsuario" class="btn btn-success" type="submit" >Guardar</button>
            </form>
        </div>
    </div>
</div>


<script type="text/javascript">

    $(function () {
        var prog_interes = document.getElementById('prog_interes');

        prog_interes.addEventListener('click', ocultarInput);


        function ocultarInput()
        {
            //console.info("aca");
            var seleccion = document.getElementById('prog_interes');
            var idPrograma = seleccion.options[seleccion.selectedIndex].value;
            
            if (idPrograma == 9) {
                console.info(idPrograma);
                $('#otro_prog_interes').show();
            }

            if (idPrograma != 9) {
                $('#otro_prog_interes').hide();
            }
        }
    });


    $(document).ready(function () {
        var MaxInputs = 8; //Número Maximo de Campos
        var contenedor = $("#contenedor"); //ID del contenedor
        var AddButton = $("#agregarCampo"); //ID del Botón Agregar

        //var x = número de campos existentes en el contenedor
        var x = $("#contenedor div").length + 1;
        var FieldCount = x - 1; //para el seguimiento de los campos

        $(AddButton).click(function (e) {
            if (x <= MaxInputs) //max input box allowed
            {
                FieldCount++;
                //agregar campo
                $(contenedor).append('<div><textarea class="form-control validate[required]" name="observa[]" id="campo_' + FieldCount + '" placeholder="Observació ' + FieldCount + '" rows="3"></textarea><a href="#" class="eliminar">&times;</a></div>');
                x++; //text box increment
            }
            return false;
        });

        $("body").on("click", ".eliminar", function (e) { //click en eliminar campo
            if (x > 1) {
                $(this).parent('div').remove(); //eliminar el campo
                x--;
            }
            return false;
        });
    });
</script>