<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<link href="https://cdn.datatables.net/1.10.7/css/jquery.dataTables.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" >
    $(document).ready(function() {
    $('#example').dataTable( {
        "pagingType": "full_numbers"
    } );
} );
</script>

<?php 
    $title = "Estudiantes";
    $this->headTitle($title);
//    foreach ($usuarios as $usuario){
//        var_dump($usuario); echo "<br/>";
//    }
//    exit();
    
?>

<h1 class="title"><?= $this->escapeHtml($title); ?></h1>

<p>
    <a class="btn btn-success" href="<?php echo $this->url('usuarios', array('action' => 'add')); ?>">Agregar Estudiante</a>
</p>

<table id="example" class="display"  class="table tablesorter">
    <thead style="border: 2px #e0e0e0 solid;">
        <tr>
            <th class="th_table table-estudiantes">Id</th>
            <th class="th_table table-estudiantes">Nombre</th>
            <th class="th_table table-estudiantes">Correo Electrónico </th>
            <th class="th_table table-estudiantes">Teléfono </th>
            <th class="th_table table-estudiantes">Código</th>
            <th class="th_table table-estudiantes">Programa Académico / <br/> Universidad</th>
            <th class="th_table table-estudiantes">Semestre</th>
            <th class="th_table table-estudiantes">Programa Interés </th>
            <th class="th_table table-estudiantes">Compromisos</th>
            <th class="th_table table-estudiantes">Observaciones</th>
            <th class="th_table table-estudiantes">Estado</th>
            <th class="th_table table-estudiantes">Fecha de Registro</th>
            <th class="th_table table-estudiantes">Editar</th>
            <th class="th_table table-estudiantes">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($usuarios as $usuario): 
            $estado= "";
            if($usuario->ESTADO == 1){
                $estado = "Consulta";
            }else if($usuario->ESTADO == 2){
                $estado = "Tramite";
            }else if($usuario->ESTADO == 3){
                $estado = "Paso a Movilidad";
            }else if($usuario->ESTADO == 4){
                $estado = "Se respondio";
            }else if($usuario->ESTADO == 5){
                $estado = "No paso nada";
            }
            ?>
        <tr>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->id) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->name) . " " . $this->escapeHtml($usuario->last_name) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->email) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->telefono) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->cod_estud) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->carrera) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->semestre) ?></td>
        <td class="th_table"><?php echo $this->escapeHtml($usuario->prog_interes) ?></td>
        <td class="th_table" style="word-wrap: break-word; width: 250px; height: 5px; "><?php echo $this->escapeHtml($usuario->compromisos) ?></td>
        <td class="th_table" style="word-wrap: break-word; width: 100px;"><?php echo $this->escapeHtml($usuario->observaciones) ?></td>
        <td class="th_table" style="word-wrap: break-word; width: 100px;"><?php echo $this->escapeHtml($estado) ?></td>
        <td class="th_table" style="word-wrap: break-word; width: 100px;"><?php echo $this->escapeHtml($usuario->FECHA_CREACION) ?></td>
        <td class="th_table"><a href="<?php echo $this->url('usuarios', array('action' => 'edit', 'id' => $usuario->id)); ?>"><img src='<?php echo $this->basePath('img/editar.png') ?>' ></a></td>
        <td class="th_table"><a href="<?php echo $this->url('usuarios', array('action' => 'delete', 'id' => $usuario->id)); ?>"><img src='<?php echo $this->basePath('img/eliminar.png') ?>' ></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>


