<?php
$title = "Agregar nuevo Factor.";
$this->headTitle($title);
?>
<h1> <?= $this->escapeHtml($title); ?> </h1>


<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-es.js"></script>


<div id="container ">
    <div class="row-fluid top-buffer">
        <div class="col-lg-6 col-lg-offset-3 text-center">
            <form action="<?php echo $this->basePath() ?>/factores/add" id="formadd" method="post" name="formadd" >
                <table id="tblprod" class="table table-hover table-bordered">
                    <tr>
                        <td>Nombre</td>
                        <td><input type="text" id="name" name="name" /> </td>
                    </tr>
                </table>
                <button id="addFactor" class="btn btn-success" type="submit" >Guardar</button>
            </form>

        </div>
    </div>

    
    <div class="row-fluid top-buffer">
        <div class="col-lg-6 col-lg-offset-3 text-center">
            <form action="<?php echo $this->basePath() ?>/factores/sumar" id="miform" method="post" name="miform" >
                <table id="tblprod" class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Codigo Producto</th>
                            <th>Nombre</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>
                                <div class="form-group col-lg-12">
                                    <input class="form-control validate[required]"name="nombre" id="nombre_factor[]"/>
                                    <input name="id_f" id="id_f" value="1"/>
                                </div>
                            </td>
                        </tr>

                    </tbody>
                </table>
                <!--<button id="btnadd" class="btn btn-primary">Agregar Nuevo</button>-->
                <button id="btnsubmit" type="submit" class="btn btn-success">Guardar</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#addFactor").submit(function (e) {
            console.info("aca llega");
            var frm = $(this);
            var data = $(this).serialize();
            e.preventDefault();
            var num1 = $("name").val();


            if (num1 !== "") {
                $.ajax({
                    url: $("#formadd").attr('action'),
                    type: $("#formadd").attr('method'),
                    data: {m1: num1},
                    success: function (data) {
                        $("#resultado").val(data.resultad)
                    }
                });
            }
        });

    });



    $(function () {
        $("#btnsubmit").submit(function (e) {

            console.info("Hola");
            var frm = $(this);
            var data = $(this).serialize();
            e.preventDefault();
            var num1 = $("nombre_factor").val();
            var num2 = $("id_f").val();

            if (num1 !== "") {
                $.ajax({
                    url: $("#miform").attr('action'),
                    type: $("#miform").attr('method'),
                    data: {m1: num1, m2: num2},
                    success: function (data) {
                        $("#resultado").val(data.resultad)
                    }
                });
            }
        });

    });



    $(function () {
        var count = 1;
        jQuery("#miform").validationEngine({promptPosition: "centerRight:0,-5"});

        $(document).on("click", "#btnadd", function (event) {
            count++;
            $('#tblprod tr:last').after('<tr><td>' + count + '</td><td><div class="form-group col-lg-12"><input class="form-control validate[required]" name="prod[]" /></div></td></tr>');
            event.preventDefault();
        });

    });
</script>














