<script>
    $(function () {
        $('table').tablesorter({
            widgets: ['zebra', 'columns'],
            usNumberFormat: false,
            sortReset: true,
            sortRestart: true
        });
    });
</script>

<?php
// module/Album/view/album/album/index.phtml:

$title = 'Factores';
$this->headTitle($title);
//var_dump(__DIR__); exit();
include __DIR__ . '\..\..\..\..\menu.phtml';
?>

<div class="container-view">
<h1 class="title"><?php echo $this->escapeHtml($title); ?></h1>

<p ><a class="btn btn-success" style="margin-left: 5%;" href="<?php

    if(isset($_GET['subpage'])){
        echo $this->url('factores', array(
        'action' => 'add',
        'id' => $_GET['subpage']));
    }else{
        echo $this->url('factores', array(
        'action' => 'add'));
    }
    
    ?>">Agregar nuevo factor...</a></p>

<table class="table tablesorter">
    <thead style="border: 2px #e0e0e0 solid;">
        <tr>
            <th class="th_table">Id</th>
            <th class="th_table">Nombre</th>
            <th class="th_table">Editar</th>
            <th class="th_table">Eliminar</th>
            <th class="th_table">Ver Caracteristicas</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($factores as $factor) : ?>
            <tr>
                <td class="th_table"><?php echo $this->escapeHtml($factor->id); ?></td>
                <td class="th_table"><?php echo $this->escapeHtml($factor->name); ?></td>
                <td class="th_table">
                    <a href="<?php echo $this->url('factores', array('action' => 'edit', 'id' => $factor->id));
        ?>"><img src='<?php echo $this->basePath('img/editar.png') ?>' ></a>
                </td>
                <td class="th_table">
                    <a href="<?php echo $this->url('factores', array('action' => 'delete', 'id' => $factor->id, 'idComponente' => $_GET['subpage']));
        ?>"><img src='<?php echo $this->basePath('img/eliminar.png') ?>' ></a>
                </td>
                <td class="th_table" style="text-align: center; width: 110px;">
                    <a href="<?php echo $this->url('caracteristica', array('action' => 'index', 'id' => $factor->id));
        ?>"><img src='<?php echo $this->basePath('img/ver.png') ?>' ></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<div class="btn-atras">
    <a style="color: white; cursor: pointer;" href="<?php echo $this->url('componentes', array('action' => 'index'));
        ?>">Atras</a>
</div>
</div>
