<?php
?>
<style type="text/css">

    
      
    
.menu{
    
    //position: fixed;
   // margin-left: -250px;
}

a.menu {
	display:inline-block;
	padding:0px 12px;
	margin:0px 8px;
        margin-top: 20px;
}




@media all and (max-width: 1200px) {
	menu {
		margin-left: 0px;
	}
}



</style>

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<div class="menu">
    <ul>
        <li>
            <a href="<?php echo $this->url('presupuestado', array('action' => 'presupuestado')); ?>">PDI Presupuestado</a> 
        </li>
        <li>
            <a href="">PDI Ejecutado</a> 
        </li>
        <li>
            <a href="">BSC ORI</a> 
        </li>
        <li>
            <a href="">PDI Presupuestado</a> 
        </li>
    </ul>
</div>

