<?php
$title = "Agregar nuevo Componente";
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-es.js"></script>

<div id="container">
    <div class="row-fluid top-buffer">
        <div class="text-center">
            <form action="<?php echo $this->basePath() ?>/componentes/add" id="formadd" method="post" name="formadd">
                <table id="tblprod" class="table table-hover table-bordered">
                    <tr>
                        <td><b>Nombre Componente</b></td>
                        <td><input class="form-control validate[required]" type="text" id="name" name="name" /></td>
                    </tr>
                </table>
                <button id="addComponente" class="btn btn-success" type="submit">Guardar</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        jQuery("#formadd").validationEngine({promptPosition: "centerRight:0,-5"});
        
        $("#addComponente").submit(function (e) {
            console.info("aca llega");
            var frm = $(this);
            var data = $(this).serialize();
            e.preventDefault();
            var num1 = $("name").val();


            if (num1 !== "") {
                $.ajax({
                    url: $("#formadd").attr('action'),
                    type: $("#formadd").attr('method'),
                    data: {m1: num1},
                    success: function (data) {
                        $("#resultado").val(data.resultad)
                    }
                });
            }
        });

    });
</script>

