<script>
    $(function () {
        $('table').tablesorter({
            widgets: ['zebra', 'columns'],
            usNumberFormat: false,
            sortReset: true,
            sortRestart: true
        });
    });
</script>
<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>

<?php

//header("Content-Type: application/vnd.ms-excel");

//header("Expires: 0");

//header("Cache-Control: must-revalidate, post-check=0, pre-check=0");

//header("content-disposition: attachment;filename=INFORME_CONTENCIÓN.xls");
?>

<?php


$title = 'Tabla de Indicadores';
$this->headTitle($title);
include __DIR__ . '\..\..\..\..\menu.phtml';
?>
<div class="container-view">
    <h1 class="title"><?php echo $this->escapeHtml($title); ?></h1>
    <?php
    $getNameIndicadores = $getIndicadores->getIndicadores();
    foreach ($getNameIndicadores as $indicadores) {
        ?>
    <form action="<?php echo $this->basePath() ?>/componentes/bscori" method="POST" enctype="multipart/form-data">
        <table >
            <tr>
                <td><b>Filtrar por:</b></td>
                <td></td>
                <td><b>&nbsp;&nbsp;&nbsp;&nbsp; Año</b></td>
                <td>
                    <select name="anio" id="anio">
                        <option value="0">--------</option>
                        <?php
                        $date = date("Y");
                        if (date("Y") == 2016) {
                            $anio = $date - 12;
                        } else {
                            $anio = $date - 1;
                        }

                        $dto = $date ;

                        for ($i = $anio; $i <= $dto; $i++) {
                            ?>
                            <option value="<?= $anio ?>"><?= $anio ?></option>
                            <?php
                            $anio++;
                        }
                        ?>
                    </select> 
                </td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp; <button id="btnFiltar" class="btn btn-success" type="submit">Filtrar</button></td>
            </tr>
        </table>
        
    </form>
        <div id="dvData">
        <table class="table tablesorter">
            <thead style="border: 2px #e0e0e0 solid; ">
                <tr>
                    <th rowspan="3" style="padding-bottom: 43px;" class="th_table componente-nombre"><?= $indicadores->NAME ?></th>
                    <th colspan="6" class="th_table color-table">Cumplimiento  <?php echo $dateFil; ?></th>
                </tr>
                <tr>
                    <th colspan="2" class="th_table color-table">Ejecutado</th>
                    <th colspan="2" class="th_table color-table">Presupuestado</th>
                    <th colspan="2" class="th_table color-table">% Cumplimiento</th>
                </tr>  
                <tr>
                    <th class="th_table color-table">Sem A</th>
                    <th class="th_table color-table">Sem B</th>
                    <th class="th_table color-table">Sem A</th>
                    <th class="th_table color-table">Sem B</th>
                    <th class="th_table color-table">Sem A</th>
                    <th class="th_table color-table">Sem B</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $componente = $getIndicadores->getOneComponente(1, 0);
                foreach ($componente as $getComponente) {
                    $idComponente = $getComponente->id;
                }
                $getFactores = $factor->getAllFactorComponente($idComponente);
                $i = 0;
                //foreach ($getFactores as $getFactor) {

                $porcenta1= 0;
                $porcenta2= 0;
                $getSubIndicadores = $getIndicadores->getSubIndicadores($indicadores->ID);
                
                foreach ($getSubIndicadores as $subIndicadores) { /*VAR_DUMP($subIndicadores);*/  ?>
                <tr>
                    <?php if($subIndicadores->ID >= 11){ ?>
                        <td class="th_table"><a style="  color: black;" href="<?php echo $this->url('componentes', array('action' => 'bscfactor', 'id' => $subIndicadores->ID_FACTOR, 'anio' => $dateFil, 'idIndicador' => $subIndicadores->ID))?>">  <?=   $subIndicadores->NAME ?> </a></td>
                    <?php }else{ ?> 
                        <td class="th_table"><a style="  color: black;" href="<?php echo $this->url('componentes', array('action' => 'bscfactor', 'id' => $subIndicadores->ID, 'anio' => $dateFil, 'idIndicador' => $subIndicadores->ID))?>">  <?=   $subIndicadores->NAME ?> </a></td>
                    <?php }
                        //$date = 2015;
                        //echo $subIndicadores->ID_FACTOR . " este <br/>";
                        $getSumEjecutado = $ejecutado->sumEjecutadoCaracteristica($subIndicadores->ID_FACTOR, $dateFil, $subIndicadores->IDCOMPONENTE);
                        foreach ($getSumEjecutado as $sumEjecutado) {
                            //echo "Hola <br/>" ;
                            ?>

                            <td class="th_table"><?= $sumEjecutado->semestreaa ?></td>
                            <td class="th_table"><?= $sumEjecutado->semestrebb ?></td>

                            <?php
                            $getSumPresupuestado = $presupuestado->getSumPresupuestado($subIndicadores->ID_FACTOR, $dateFil, $subIndicadores->IDCOMPONENTE);
                            foreach ($getSumPresupuestado as $sumPresupuestado) {
                                //var_dump($sumPresupuestado); exit();
                                ?>
                                <td class="th_table"><?= $sumPresupuestado->semestreaa ?></td>
                                <td class="th_table"><?= $sumPresupuestado->semestrebb ?></td>
                                <?php
                            }
                            
                        }
                        
                        if (!isset($sumPresupuestado->semestreaa)) {
                            echo "<td class='th_table'>0</td>";
                        }

                        if (!isset($sumPresupuestado->semestrebb)) {
                            echo "<td class='th_table'>0</td>";
                        }
                        if (!isset($sumEjecutado->semestreaa)) {
                            echo "<td class='th_table'>0</td>";
                        }
                        if (!isset($sumEjecutado->semestrebb)) {
                            echo "<td class='th_table'>0</td>";
                        }
                        //echo "este" . $sumEjecutado->semestrebb . "<br/>" ;
//                        if($sumEjecutado->semestreaa == 0){
//                            echo "<td class='th_table'>4...0</td>";
//                        }
//                        
//                        if($sumEjecutado->semestrebb == 0){
//                            echo "<td class='th_table'>4...0</td>";
//                        }
//                        if($sumPresupuestado->semestrebb == 0){
//                            echo "<td class='th_table'>4...0</td>";
//                        }
//                        if($sumPresupuestado->semestreaa == 0){
//                            echo "<td class='th_table'>4...0</td>";
//                        }
                        if (isset($sumEjecutado->semestreaa)) { 
                            
                            $porcenta1 = ceil(($sumEjecutado->semestreaa / $sumPresupuestado->semestreaa) * 100);
                            $porcenta2 = ceil(($sumEjecutado->semestrebb / $sumPresupuestado->semestrebb) * 100);
                            $sumEjecutado->semestreaa = 0;
                            $sumEjecutado->semestrebb = 0;
                            if($porcenta1 >= 100){
                                $color = "#3ADF00";
                            }else if( $porcenta1 >= 80){
                                $color = "#FFFF00";
                            }else if($porcenta1 < 80){
                                $color = "#FF0000";
                            }
                            
                            if($porcenta1 == 0){
                                echo "<td class='th_table'>0</td>";
                                echo "<td class='th_table'>0</td>";
                                echo "<td class='th_table'>0</td>";
                                echo "<td class='th_table'>0</td>"; 
                            }
                            //$sumEjecutado->semestreaa = 0;
                            
                            ?>
                                <td class="th_table" style="background-color: <?= $color ?>"><?= $porcenta1 ?> %</td>
                            <td class="th_table"><?= $porcenta2 ?> %</td>
                        </tr>
                        <?php } else { 
                        ?>
                    <td class="th_table">0 %</td>
                    <td class="th_table">0 %</td>
                    </tr>
                <?php
                }
                
                //$sumEjecutado->semestrebb = 0;
                //echo $porcenta2 ."  ---- " .$porcenta1 . "<br/>" ;
                $porcenta1 = 0;
                $porcenta2 = 0;
                //$i = $getFactor->id;
                //}
            }
            //}
            //}
            
            //}
            ?>
        <?php ?>
            </tbody>
        </table>
<?php } ?>
    </div>
</div>
<input type="button" id="btnExport" value=" Export Table data into Excel " />


<?php
//header('Content-type: application/vnd.ms-excel');
//header("Content-Disposition: attachment; filename=nombre_del_archivo.xls");
?>
<!--Content-Disposition: filename=ficheroExcel.xls-->
<!--Content-Disposition: attachment; filename=nombre_del_archivo.xls-->
<script>
    $("#btnExport").click(function(e) {
        window.open('data:application/vnd.ms-excel; charset=ISO-8859-1, ' + encodeURIComponent($('#dvData').html()));
//        window.open('Content-type: application/vnd.ms-excel, name="excel" ' + encodeURIComponent($('#dvData').html()));
        e.preventDefault();
    });
    </script>