<?php

$title = "Eliminar Componente";
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>¿Seguro deseas eliminar el componente
    '<?php echo $this->escapeHtml($componente->name); ?>' ?
</p>
<?php 
$url = $this->url('componentes', array(
   'action' => 'delete',
    'id' => $this->id
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name='id' value="<?php echo (int) $componente->id;?>" />
        <input type="submit" name='del' value="Yes" />
        <input type="submit" name='del' value="No" />
    </div>
</form>

