<?php
$title = "Modificación de Administrador";
$this->headTitle($title);
$form = $this->form;
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-es.js"></script>

<div id="container" style="  width: 80%; margin-left: 10%;">
    <div class="row-fluid top-buffer">
        <div class=" text-center">
            <form action="<?php echo $this->basePath() ?>/admin/edit" id="formadd" method="post" name="formadd">
                <table id="tblprod" class="table table-hover table-bordered">
                    <?php foreach ($admin as $getAdmin){ ?>
                    <tr>
                        <td class="td_table">Nombre</td>
                        <td><input class="form-control validate[required]" type="text" name="name" id="name" value="<?= $getAdmin->nombre ?>" /></td>
                    <input type="hidden" id="id" name="id" value="<?= $getAdmin->id ?>" />
                    </tr>
                    <tr>
                        <td class="td_table">Apellido</td>
                        <td><input class="form-control validate[required]" type="text" name="apellido" id="apellido" value="<?= $getAdmin->apellido ?>" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Dirección</td>
                        <td><input class="form-control validate[required]" type="text" name="direccion" id="direccion" value="<?= $getAdmin->direccion ?>" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Telefono</td>
                        <td><input class="form-control validate[required]" type="text" name="telefono" id="telefono" value="<?= $getAdmin->telefono ?>" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Celular</td>
                        <td><input class="form-control validate[required]" type="text" name="celular" id="celular" value="<?= $getAdmin->celular ?>" /></td>
                    </tr>
                    <tr>
                        <td class="td_table">Email</td>
                        <td><input class="form-control validate[required]" type="text" name="email" id="email" readonly="readonly" value="<?= $getAdmin->email ?>" /></td>
                    </tr>
                    <?php } ?>
                </table>
                <button id="addAdmin" class="btn btn-success" type="submit" >Guardar</button>
            </form>
        </div>
    </div>
</div>


