<script>
    $(function () {
        $('table').tablesorter({
            widgets: ['zebra', 'columns'],
            usNumberFormat: false,
            sortReset: true,
            sortRestart: true
        });
    });
</script>

<?php
// module/Album/view/album/album/index.phtml:

$title = 'Componentes';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php
    echo $this->url('album', array(
        'action' => 'add'));
    ?>">Add new album</a></p>

<table class="table tablesorter">
    <thead>
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($albums as $album) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($album->title); ?></td>
                <td><?php echo $this->escapeHtml($album->artist); ?></td>    <td>
                    <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id));
    ?>">Edit</a>
                    <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id));
    ?>">Delete</a>
                </td>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>

