<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        
        <link rel="shortcut icon" href="<?= $this->basePath('img/ori.png')?>">

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/jquery.dataTables.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-1.11.1.min.js'))
                ->prependFile($this->basePath('js/jquery.tablesorter.js'))
                ->prependFile($this->basePath('js/jquery-1.3.2.min.js'))
//                ->prependFile($this->basePath('js/jquery.table2excel.js'))
                //->prependFile($this->basePath('js/dataTables.bootstrap.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                //->prependFile($this->basePath('js/jquery.dataTables.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <?php 
    //session_start();
    if (isset($_SESSION['user'])) { 
                    
    }
    ?>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <?php
                
                if (!isset($_SESSION['user'])) { 
                    ?>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/ori-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;</a>
                <?php } ?>
                </div>

                <?php
                
                if (isset($_SESSION['user'])) { 
                    
                    ?>
                <a class="navbar-brand" ><img src="<?php echo $this->basePath('img/ori-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;</a>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('usuarios') ?>"><?php echo $this->translate('Estudiantes') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('componentes') ?>"><?php echo $this->translate('Componentes') ?></a></li>
<!--                            <li class="active"><a href="<?php // echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>-->
                            <li class="active"><a href="<?php echo $this->url('login', array('action' => 'index'));
            ?>"><?php echo $this->translate('Logout') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('admin', array('action' => 'index'));
            ?>"><?php echo $this->translate('Usuario') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                <?php } ?>

                
            </div>
        </nav>
        <div class="container">
        <?php echo $this->content; ?>

            <footer>
                <!--<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>-->
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
