<?php
$title = "Agragar Ejecutado";
$this->headTitle($title);
$form = $this->form;
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/jquery.validationEngine.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jQuery-Validation-Engine/2.6.4/languages/jquery.validationEngine-es.js"></script>

<div id="container" style="  width: 80%; margin-left: 10%;">
    <div class="row-fluid top-buffer">
        <div class=" text-center">
            <form action="<?php echo $this->basePath() ?>/ejecutado/add" method="POST" enctype="multipart/form-data">
                <table id="tblprod" class="table table-hover table-bordered">
                    <tr>
                        <td class="td_table">Año</td>
                    <input type="hidden" value="<?= $idCaracteristica ?>" name="idCaracteristica" id="idCaracteristica" />
                        <td>
                            <select name="anio" id="anio" class="form-control validate[required]">
                                <?php
                                $date = date("Y");
                                if (date("Y") == 2016) {
                                    $anio = $date - 12;
                                } else {
                                    $anio = $date - 1;
                                }

                                $dto = $date + 3;

                                for ($i = $anio; $i <= $dto; $i++) {
                                    ?>
                                    <option value="<?= $anio ?>"><?= $anio ?></option>
                                    <?php
                                    $anio++;
                                }
                                ?>

                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Semestre</td>
                        <td>
                            <select name="semestre" id="semestre" class="form-control validate[required]">
                                <option value="A">A</option>
                                <option value="B">B</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="td_table">Archivo</td>
                        <td>
                            <input type="file" name="archivo" id="archivo" />
                        </td>
                    </tr>
                    <input type="hidden" value="<?= $this->basePath() . "/img" ?>" id="url" name="url"/>
                    <tr>
                        <td class="td_table">Calificación</td>
                        <td>
                            <select name="calificacion" id="calificacion" class="form-control validate[required]">
                                <option value="0">0</option>
                                <option value="1.0">1.0</option>
                                <option value="1">1</option>
                            </select>
                        </td>
                    </tr>
                </table>
                <button id="addEjecutado" class="btn btn-success" type="submit">Guardar</button>
            </form>


        </div>
    </div>
</div>



<!--
<script type="text/javascript">
    $(function () {

        var miVariable = "Esto es una variable en JS";
        document.cookie = 'var=' + miVariable;
        var factor = document.getElementById('factor');

        factor.addEventListener('click', getCaracteristic);

        $(factor).click(function (e) {


            var seleccion = document.getElementById('factor');
            var idFactor = seleccion.options[seleccion.selectedIndex].value;




        });


    });
</script>-->

