<script type="text/javascript">
    $(document).ready(function () {
        $('#example').dataTable();
    });
</script>

<?php
$title = 'PDI Ejecutado';
$this->headTitle($title);
include __DIR__ . '\..\..\..\..\menu.phtml';
?>



<div class="container-view">
    <h1 class="title"><?php echo $this->escapeHtml($title); ?></h1>
    <p>
        <a class="btn btn-success" href="<?php echo $this->url('ejecutado', array('action' => 'add')); ?>">Agregar Ejecutado</a>
    </p>
    <table id="example" class="table table-striped table-bordered">
        <thead style="border: 2px #e0e0e0 solid;">
            <tr>
                <th rowspan="2" class="th_table">Componentes</th>
                <th rowspan="2" class="th_table">Factor</th>
                <th rowspan="2" class="th_table">Caracteristica</th>
                <?php
                $datePresupuestado = $ejecutado->getDateEjecutado();
                foreach ($datePresupuestado as $date) {
                    $fehca = $date->fecha;
                    ?>
                    <th colspan="2" class="th_table"><?php echo $fehca ?></th>

                    <?php
                }
                ?>
            </tr>
            <tr> 
                <?php
                $datePresupuestado2 = $ejecutado->getDateEjecutado();
                foreach ($datePresupuestado2 as $date2) {
                    ?>

                    <th>Sem A</th>
                    <th>Sem B</th>

                    <?php
                }
                ?>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($componentes as $componente) {
                $currentFactores = $factores->getAllFactorComponente($componente->id);
                $nCarRows = 0;
                $f = 0;
                $row = "<tr>"
                        . "<td rowspan='%d'>" . $componente->name . "</td>";
                foreach ($currentFactores as $factor) {
                    $currentCaracteristicas = $caracteristicas->getCaracteristicaFactor($factor->id);
                    $nCarRows += $currentCaracteristicas->count();
                    if ($f === 0) {
                        $row .= "<td rowspan='" . $currentCaracteristicas->count() . "'>" . $factor->name . "</td>";
                    } else {
                        $row .= "<tr><td rowspan='" . $currentCaracteristicas->count() . "'>" . $factor->name . "</td>";
                    }
                    $f++;
                    $c = 0;
                    $date = 2014;

                    foreach ($currentCaracteristicas as $caracteristica) {
                        if ($c === 0) {
                            $row .= "<td>" . $caracteristica->CARACTERISTICA . "</td>";
                        } else {
                            $row .= "<tr><td>" . $caracteristica->CARACTERISTICA . "</td>";
                        }
                        $c++;
                        $algo = "si";
                        for ($i = $date; $i <= date("Y"); $i++) {
                            $currentEjecutado = $ejecutado->getEjecutadoCaracteristica($caracteristica->ID, $i);
                            foreach ($currentEjecutado as $dateEjecutado) {
                                $algo = "no";
                                $row .= "<td>" . $dateEjecutado->semestreaa . "</td>"
                                        . "<td>" . $dateEjecutado->semestrebb . "</td>";
                            }
                            if ($algo == "si") {
                                $row .= "<td>0</td>";
                                $row .= "<td>0</td>";
                            }
                        }
                        //$date++;
                        $row .= "</tr>";
                    }
                }
                echo sprintf($row, $nCarRows);
            }
            
            
            
            
            foreach ($componentesEjecutado as $componente) {
                $currentFactores = $factores->getAllFactorComponente($componente->id);
                $nCarRows = 0;
                $f = 0;
                $row = "<tr>"
                        . "<td rowspan='%d'>" . $componente->name . "</td>";
                foreach ($currentFactores as $factor) {
                    $currentCaracteristicas = $caracteristicas->getCaracteristicaFactor($factor->id);
                    $nCarRows += $currentCaracteristicas->count();
                    if ($f === 0) {
                        $row .= "<td rowspan='" . $currentCaracteristicas->count() . "'>" . $factor->name . "</td>";
                    } else {
                        $row .= "<tr><td rowspan='" . $currentCaracteristicas->count() . "'>" . $factor->name . "</td>";
                    }
                    $f++;
                    $c = 0;
                    $date = 2014;

                    foreach ($currentCaracteristicas as $caracteristica) {
                        $url = $this->url('ejecutado', array('action' => 'add', 'id' => $caracteristica->ID));
                        if ($c === 0) {
                            $row .= "<td><a style='color: black;' href='". $url ."'>" . $caracteristica->CARACTERISTICA . "</a></td>";
                        } else {
                            $row .= "<td><a style='color: black;' href='". $url ."'>" . $caracteristica->CARACTERISTICA . "</a></td>";
                        }
                        $c++;
                        $algo = "si";
                        for ($i = $date; $i <= date("Y"); $i++) {
                            $currentEjecutado = $getejecutado->getEjecutadoM($caracteristica->ID, $i);
                            foreach ($currentEjecutado as $dateEjecutado) { //id
                                $urla = $this->url('ejecutado', array('action' => 'edit', 'id' => $dateEjecutado->semestreaaid));
                                $urlb = $this->url('ejecutado', array('action' => 'edit', 'id' => $dateEjecutado->semestrebbid));
                                $algo = "no";
                                $row .= "<td> <a style='color: black;' href='". $urla ."'>" . $dateEjecutado->semestreaa . "</a></td>"
                                     .  "<td><a style='color: black;' href='". $urlb ."'>" . $dateEjecutado->semestrebb . "</a></td>";
                            } 
                            if ($algo == "si") {
                                $row .= "<td>0</td>";
                                $row .= "<td>0</td>";
                            }
                        }
                        //$date++;
                        $row .= "</tr>";
                    }
                }
                echo sprintf($row, $nCarRows);
            }
            ?>
        </tbody>
    </table>
</div>

